name: deploy common package

on:
  push:
    branches:
      - master
    paths:
      - "common/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: cd common && npm ci

      - name: Install dependencies
        run: cd common && npm install

      - name: Build module
        run: cd common && npm run build

      - name: Patch module
        run: cd common && npm version patch

      - name: Commit change
        run: |
          git config --global user.name 'BladimirOrihuela-Hexaware'
          git config --global user.email 'BladimirOrihuela-Hexaware@users.noreply.github.com'
          git add .
          git commit -am "bump commons"
          git push

      - name: Publish module
        run: cd common && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
