name: deploy common package

on:
  push:
    branches:
      - master
    paths:
      - "common/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: cd common && npm install

      - name: Build module
        run: cd common && npm run build

      - name: Patch module
        run: cd common && npm run patch

      # - run: cd common && npm ci
      # - run: cd common && npm publish --access public
      # env:
      #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: cd common && npm ci
      - run: cd common && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
